"""Adapter for Vbee's Batch Text-to-Speech API."""

from typing import Any
from urllib.parse import urlparse

import httpx

from app.core.config import settings

_BATCH_TTS_URL = "https://vbee.vn/api/v1/tts"
_REALTIME_TTS_URL = "https://api.vbee.vn/v1/tts"


class VbeeNotConfiguredError(RuntimeError):
    """Raised when the server has not been given the Vbee credentials."""


class VbeeError(RuntimeError):
    """Raised for a provider or provider-response failure."""


def _api_url() -> str:
    """Return the Batch TTS endpoint used by Standard, Special and VIP plans."""
    configured = settings.VBEE_API_URL.strip().rstrip("/")
    return _BATCH_TTS_URL if not configured or configured == _REALTIME_TTS_URL else configured


def _media_type() -> str:
    return {
        "mp3": "audio/mpeg",
        "wav": "audio/wav",
        "pcm": "audio/pcm",
    }.get(settings.VBEE_AUDIO_TYPE.lower(), "audio/mpeg")


def _error_message(response: httpx.Response) -> str:
    try:
        payload: Any = response.json()
    except ValueError:
        return f"Vbee returned HTTP {response.status_code}"

    if isinstance(payload, dict):
        for key in ("message", "error_message", "detail"):
            if isinstance(payload.get(key), str):
                return payload[key]
    return f"Vbee returned HTTP {response.status_code}"


def _validate_configuration() -> None:
    missing = [
        name
        for name, value in {
            "VBEE_APP_ID": settings.VBEE_APP_ID,
            "VBEE_TOKEN": settings.VBEE_TOKEN,
            "VBEE_VOICE_CODE": settings.VBEE_VOICE_CODE,
        }.items()
        if not value.strip()
    ]
    if missing:
        raise VbeeNotConfiguredError(
            "Vbee TTS is not configured. Missing: " + ", ".join(missing)
        )


def _audio_link(payload: Any) -> str:
    if not isinstance(payload, dict) or payload.get("status") != 1:
        message = payload.get("message") if isinstance(payload, dict) else None
        raise VbeeError(message if isinstance(message, str) else "Vbee could not create audio")

    result = payload.get("result")
    link = result.get("audio_link") if isinstance(result, dict) else None
    if not isinstance(link, str) or not link:
        raise VbeeError("Vbee returned no audio link")

    parsed = urlparse(link)
    hostname = (parsed.hostname or "").lower()
    if parsed.scheme != "https" or not (
        hostname == "vbee.vn" or hostname.endswith(".vbee.vn")
    ):
        raise VbeeError("Vbee returned an invalid audio link")
    return link


async def synthesize(text: str) -> tuple[bytes, str]:
    """Generate and download a short MP3/WAV pronunciation through Batch TTS."""
    _validate_configuration()
    normalized_text = text.strip()
    if not normalized_text:
        raise VbeeError("Cannot synthesize empty text")
    if len(normalized_text) > 300:
        raise VbeeError("Vbee TTS supports at most 300 characters per request")

    payload = {
        "app_id": settings.VBEE_APP_ID,
        "response_type": "direct",
        "input_text": normalized_text,
        "voice_code": settings.VBEE_VOICE_CODE,
        "audio_type": settings.VBEE_AUDIO_TYPE,
        "bitrate": settings.VBEE_BITRATE,
        "speed_rate": settings.VBEE_SPEED_RATE,
    }
    headers = {
        "Authorization": f"Bearer {settings.VBEE_TOKEN}",
        "Content-Type": "application/json",
    }

    try:
        async with httpx.AsyncClient(timeout=30.0, follow_redirects=False) as client:
            create_response = await client.post(_api_url(), json=payload, headers=headers)
            if create_response.status_code >= 400:
                raise VbeeError(_error_message(create_response))

            audio_url = _audio_link(create_response.json())
            audio_response = await client.get(audio_url)
            for _ in range(2):
                if audio_response.status_code not in {301, 302, 303, 307, 308}:
                    break
                location = audio_response.headers.get("location")
                if not location:
                    raise VbeeError("Vbee returned an invalid audio redirect")
                audio_url = _audio_link(
                    {"status": 1, "result": {"audio_link": location}}
                )
                audio_response = await client.get(audio_url)
    except VbeeError:
        raise
    except ValueError as exc:
        raise VbeeError("Vbee returned an invalid response") from exc
    except httpx.TimeoutException as exc:
        raise VbeeError("Vbee TTS timed out") from exc
    except httpx.RequestError as exc:
        raise VbeeError("Could not reach Vbee TTS") from exc

    if audio_response.status_code >= 400:
        raise VbeeError("Could not download audio generated by Vbee")
    if not audio_response.content:
        raise VbeeError("Vbee returned an empty audio response")

    return audio_response.content, _media_type()
